### NBA API SWAR GITHUB CODE

In [ ]:
from nba_api.stats.static import players
playerList = players.get_players()
activePlayersList = []

for Counter in range(0, len(playerList)):
        
    if playerList[Counter]['is_active'] == True:
        
        activePlayersList.append(playerList[Counter])

for Counter in range(0, len(activePlayersList)):
        
    print(activePlayersList[Counter]['full_name'])

### NBA API CALLING USING PYTHON CODE

In [1]:
from bs4 import BeautifulSoup as BS
import requests as RQ
import pandas as PD
import os as OS
import os

In [7]:
URL = "https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode=PerGame&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season=1996-97&SeasonSegment=&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision=&Weight="

headerDictionary = {
    
    'User-Agent': 'Safari',
    'x-nba-stats-origin': 'stats',
    'x-nba-stats-token': 'true',
    'Referer': 'https://stats.nba.com',
    'Connection': 'keep-alive',
    'Pragma': 'no-cache',
    'Cache-Control': 'no-cache',
    'Host': 'stats.nba.com'

}

Results = RQ.get(URL, headers=headerDictionary)
resultsJSON = Results.json()

Headers = resultsJSON['resultSets'][0]['headers']
dataSet = resultsJSON['resultSets'][0]['rowSet']
dataFrame = PD.DataFrame(dataSet, columns=Headers)

dataFrame

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,CFID,CFPARAMS
0,920,A.C. Green,A.C.,1610612742,DAL,33.0,83,23,60,0.277,...,138,251,36,194,394,155,49,24,5,"920,1610612742"
1,243,Aaron McKie,Aaron,1610612765,DET,24.0,83,48,35,0.578,...,176,285,192,248,93,229,168,24,5,"243,1610612765"
2,1425,Aaron Williams,Aaron,1610612763,VAN,25.0,33,4,29,0.121,...,319,182,192,224,363,207,219,24,5,"1425,1610612763"
3,768,Acie Earl,Acie,1610612749,MIL,27.0,47,14,33,0.298,...,357,329,192,292,269,304,219,24,5,"768,1610612749"
4,228,Adam Keefe,Adam,1610612762,UTA,27.0,62,48,14,0.774,...,320,286,125,305,77,282,168,24,5,"228,1610612762"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
436,335,Willie Anderson,Willie,1610612748,MIA,30.0,28,22,6,0.786,...,416,331,192,343,211,337,219,24,5,"335,1610612748"
437,416,Willie Burton,Willie,1610612737,ATL,29.0,24,15,9,0.625,...,130,171,192,223,336,303,219,24,5,"416,1610612737"
438,1365,Xavier McDaniel,Xavier,1610612751,NJN,34.0,62,19,43,0.306,...,214,163,125,240,186,214,104,24,5,"1365,1610612751"
439,212,Yinka Dare,Yinka,1610612751,NJN,24.0,41,12,29,0.293,...,387,341,192,419,178,373,219,24,5,"212,1610612751"
440,440,Zan Tabak,Zan,1610612761,TOR,27.0,13,6,7,0.462,...,205,105,10,214,373,209,219,24,5,"440,1610612761"

In [6]:
dataFrame.to_csv('Data.csv')